name: Build Web

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Web
        run: ./gradlew wasmJsBrowserWebpack

      - name: Upload Web artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: webApp/build/distributions/*.tar.gz
