name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install Xcode Command Line Tools
        run: |
          if ! xcode-select --print-path > /dev/null 2>&1; then
            echo "Xcode Command Line Tools are not installed. Installing..."
            xcode-select --install || echo "Failed to install Xcode Command Line Tools"
          else
            echo "Xcode Command Line Tools are already installed"
          fi

      - name: Build iOS
        run: | 
          xcodebuild -allowProvisioningUpdates -workspace iosApp/iosApp.xcodeproj/project.xcworkspace -scheme iosApp -configuration Debug -sdk iphoneos -destination name='iPhone 14' build CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" DEVELOPMENT_TEAM=""
                   
      - name: Upload iOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-framework
          path: build/ios/Debug-iphonesimulator/*.app
