name: Kotlin Multiplatform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Android
        run: ./gradlew assembleRelease

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-release-apk
          path: app/build/outputs/apk/release/*.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install Xcode command line tools
        run: xcode-select --install

      - name: Build iOS
        run: ./gradlew iosArm64MainFramework

      - name: Upload iOS artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-framework
          path: build/bin/ios/arm64/debugFramework/*.framework

  build-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Desktop
        run: ./gradlew desktopJar

      - name: Upload Desktop artifacts
        uses: actions/upload-artifact@v3
        with:
          name: desktop-jar
          path: build/libs/*.jar

  generate-artifact-links:
    runs-on: ubuntu-latest
    needs: [build-android, build-ios, build-desktop]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List artifacts
        run: |
          echo "Artifact URLs for download:"
          echo "Android APK: ${{ steps.upload-android-artifacts.outputs.artifact-url }}"
          echo "iOS Framework: ${{ steps.upload-ios-artifacts.outputs.artifact-url }}"
          echo "Desktop JAR: ${{ steps.upload-desktop-artifacts.outputs.artifact-url }}"
